#!/bin/bash

function check_link() {
    f="$1"
    if [ -L ${f} ]; then
        unlink ./${f}
    fi
    ln -s /opt/homebrew/share/automake-${am_ver}/${f} ./${f}
}

am_ver="1.16"
brew install automake-${am_ver}
brew install autoconf
brew install wxwidgets
brew install sdl2

check_link "INSTALL"

check_link "compile"

check_link "config.guess"

check_link "config.sub"

check_link "depcomp"

check_link "install-sh"

check_link "missing"

echo Dependecies installed.

echo

echo Now configure your build using:
echo ./configure --with-sdl-prefix=/opt/homebrew/
   
